on:
  push:

concurrency:
  group: push-${{ github.branch }}

jobs:
  build:
    uses: webgrip/workflows/.github/workflows/php/8.2/build.yml@main

#  static-analysis:
#    uses: webgrip/workflows/.github/workflows/static-analysis.yml@main
#
#  tests:
#    uses: webgrip/workflows/.github/workflows/tests.yml@main
#  deploy:
#    needs: [ static-analysis, tests ]
#    if: always() && needs.tests.result == 'success'
#    uses: ./.github/workflows/deploy.yml
