name: "On Push"

on:
  push:
  workflow_dispatch:

concurrency:
  group: push-${{ github.branch }}

jobs:
  build:
    name: "Build"
    uses: webgrip/workflows/.github/workflows/build-dependencies/composer-install.yml@main

  static-analysis:
    name: "Static Analysis"
    needs: [ build ]
    uses: webgrip/workflows/.github/workflows/static-analysis/php.yml@main

  tests:
    needs: [ build, static-analysis ]
    uses: webgrip/workflows/.github/workflows/tests/php.yml@main

#  deploy:
#    needs: [ static-analysis, tests ]
#    if: always() && needs.tests.result == 'success'
#    uses: ./.github/workflows/deploy.yml
