name: "On Push"

on:
  push:

concurrency:
  group: push-${{ github.branch }}

jobs:
  build:
    name: "Build"
    uses: webgrip/workflows/.github/workflows/build.yml@main

  static-analysis:
    name: "Static Analysis"
    needs: [ build ]
    uses: webgrip/workflows/.github/workflows/static-analysis.yml@main

#  tests:
#    uses: webgrip/workflows/.github/workflows/tests.yml@main
#  deploy:
#    needs: [ static-analysis, tests ]
#    if: always() && needs.tests.result == 'success'
#    uses: ./.github/workflows/deploy.yml
