name: CI - Test & Build & Commit

on:
  workflow_dispatch:

jobs:
  composer-install-on-container:
    name: 'Composer install on container'
    runs-on: arc-runner-set-k8s
    container:
      image: composer:2.8.5
      env:
        COMPOSER_AUTH: >
          {
            "http-basic": {
              "repo.packagist.com": {
                  "username": "token",
                  "password": "${{ secrets.COMPOSER_TOKEN }}"
              }
            }
          }
    steps:
      - run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: vendor
          key: "composer-${{ hashFiles('**/composer.lock', '**/composer.json') }}"
      - name: 'Install dependencies'
        run: composer install --prefer-dist --no-interaction --ignore-platform-reqs
      - run: |
          ls -la
          ls -la vendor || true

  tests-run:
    needs: composer-install-on-container
    name: '${{ matrix.testsuite }}'
    runs-on: arc-runner-set-k8s
    container:
      image: php:8.2-cli
    strategy:
      fail-fast: false
      matrix:
        testsuite: [ 'Unit', 'Integration', 'Functional' ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: vendor
          key: "composer-${{ hashFiles('**/composer.lock', '**/composer.json') }}"

      - name: 'Run ${{ matrix.testsuite }} tests'
        run: |
          case "${{ matrix.testsuite }}" in
            "Unit")
              ./vendor/bin/phpunit -c ./phpunit.xml.dist --testsuite unit --fail-on-risky --coverage-php coverage/unit.cov --coverage-html coverage/unit 
              ;;
            "Integration")
              ./vendor/bin/phpunit -c ./phpunit.xml.dist --testsuite integration --fail-on-risky --exclude-group=db --coverage-php coverage/integration.cov --coverage-html coverage/integration 
              ;;
            "Functional")
              ./vendor/bin/phpunit -c ./phpunit.xml.dist --testsuite functional --fail-on-risky --coverage-php coverage/functional.cov --coverage-html coverage/functional || true
              ;;
            *)
              echo "Unknown testsuite"
              exit 1
              ;;
          esac

      - name: 'Upload coverage artifact'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.testsuite }}
          path: coverage
          retention-days: 1
  tests-2:
    needs: tests-run
    name: '${{ matrix.testsuite }}'
    runs-on: arc-runner-set-k8s
    container:
      image: php:8.2-cli
    strategy:
      fail-fast: false
      matrix:
        testsuite: [ 'Unit', 'Integration', 'Functional' ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: vendor
          key: "composer-${{ hashFiles('**/composer.lock', '**/composer.json') }}"

      - name: 'Run ${{ matrix.testsuite }} tests'
        run: |
          case "${{ matrix.testsuite }}" in
            "Unit")
              ./vendor/bin/phpunit -c ./phpunit.xml.dist --testsuite unit --fail-on-risky --coverage-php coverage/unit.cov --coverage-html coverage/unit 
              ;;
            "Integration")
              ./vendor/bin/phpunit -c ./phpunit.xml.dist --testsuite integration --fail-on-risky --exclude-group=db --coverage-php coverage/integration.cov --coverage-html coverage/integration 
              ;;
            "Functional")
              ./vendor/bin/phpunit -c ./phpunit.xml.dist --testsuite functional --fail-on-risky --coverage-php coverage/functional.cov --coverage-html coverage/functional || true
              ;;
            *)
              echo "Unknown testsuite"
              exit 1
              ;;
          esac

      - name: 'Upload coverage artifact'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.testsuite }}
          path: coverage
          retention-days: 1


